# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xiVUA90HcuoEtiIZO9hftUZUXZ_yKm1
"""

!pip install -q pypdf
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q google-generativeai

from pypdf import PdfReader

from sentence_transformers import SentenceTransformer

import faiss

import numpy as np

import google.generativeai as genai

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer

import faiss
import numpy as np

import google.generativeai as genai

from google.colab import userdata
import google.generativeai as genai

apiKey = userdata.get("GeminiKey")

genai.configure(api_key=apiKey)

print("Gemini configured successfully")

model = genai.GenerativeModel("gemini-2.5-flash")

reply = model.generate_content("Say hello in one sentence")

print(reply.text)

from google.colab import files

uploadedFiles = files.upload()

from pypdf import PdfReader

pdfFile = PdfReader(
    "NVIDIA-2025-Annual-Report.pdf"
)

pdfText = ""

for page in pdfFile.pages:

    pageText = page.extract_text()

    if pageText:
        pdfText += pageText

print("Characters extracted:", len(pdfText))

print(pdfText[:3000])

#cell8
chunkSize = 1000
overlapSize = 200

documentChunks = []

startPosition = 0

while startPosition < len(pdfText):

    endPosition = startPosition + chunkSize

    currentChunk = pdfText[
        startPosition:endPosition
    ]

    documentChunks.append(
        currentChunk
    )

    startPosition += (
        chunkSize - overlapSize
    )

print(
    "Total chunks:",
    len(documentChunks)
)

#CELL9
print(documentChunks[0][:500])

print("=" * 50)

print(documentChunks[1][:500])

from sentence_transformers import SentenceTransformer

embeddingModel = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded")

#cell11
import numpy as np

chunkVectors = embeddingModel.encode(
    documentChunks,
    show_progress_bar=True
)

chunkVectors = np.array(
    chunkVectors,
    dtype=np.float32
)

print(
    "Embedding shape:",
    chunkVectors.shape
)

import faiss

vectorDimension = chunkVectors.shape[1]

searchIndex = faiss.IndexFlatL2(
    vectorDimension
)

searchIndex.add(
    chunkVectors
)

print(
    "Vectors stored:",
    searchIndex.ntotal
)

def retrieveContext(
    question,
    topK=5
):

    questionVector = embeddingModel.encode(
        [question]
    )

    questionVector = np.array(
        questionVector,
        dtype=np.float32
    )

    distances, positions = searchIndex.search(
        questionVector,
        topK
    )

    retrievedChunks = []

    for position in positions[0]:

        retrievedChunks.append(
            documentChunks[position]
        )

    return retrievedChunks

#cell14
results = retrieveContext(
    "What are NVIDIA's major growth drivers?"
)

for number, chunk in enumerate(results):

    print(
        f"\nRESULT {number+1}"
    )

    print("=" * 50)

    print(chunk[:800])

def buildContext(question):

    retrievedChunks = retrieveContext(
        question,
        topK=5
    )

    combinedContext = ""

    for chunk in retrievedChunks:

        combinedContext += chunk
        combinedContext += "\n\n"

    return combinedContext

def askFinancialAgent(question):

    context = buildContext(
        question
    )

    prompt = f"""
You are a professional financial analyst.

Use ONLY the provided context.

Context:
{context}

Question:
{question}

Instructions:
- Give a concise answer.
- Use bullet points.
- Mention supporting evidence.
- If the answer is not present, say so.
"""

    model = genai.GenerativeModel(
        "gemini-2.5-flash"
    )

    response = model.generate_content(
        prompt
    )

    return response.text

answer = askFinancialAgent(
    "What are NVIDIA's major growth drivers?"
)

print(answer)

#cell18

def retrieveContext(
    question,
    topK=5
):

    questionVector = embeddingModel.encode(
        [question]
    )

    questionVector = np.array(
        questionVector,
        dtype=np.float32
    )

    distances, positions = searchIndex.search(
        questionVector,
        topK
    )

    results = []

    for rank, position in enumerate(
        positions[0]
    ):

        results.append(
            {
                "chunkId": rank + 1,
                "text": documentChunks[position]
            }
        )

    return results

def buildContext(question):

    retrievedChunks = retrieveContext(
        question
    )

    context = ""

    for item in retrievedChunks:

        context += (
            f"[Chunk {item['chunkId']}]\n"
        )

        context += item["text"]

        context += "\n\n"

    return context

def askFinancialAgent(question):

    context = buildContext(
        question
    )

    prompt = f"""
You are a financial analyst.

Use only the provided context.

For every statement,
mention the chunk number.

Context:
{context}

Question:
{question}
"""

    model = genai.GenerativeModel(
        "gemini-2.5-flash"
    )

    response = model.generate_content(
        prompt
    )

    return response.text

#cell21
answer = askFinancialAgent(
    "What are NVIDIA's major growth drivers?"
)

print(answer)

from google.colab import files

uploadedFiles = files.upload()

from google.colab import files

uploadedFiles = files.upload()

import os

print(os.listdir())

!pip install python-docx
from pypdf import PdfReader
from docx import Document

allDocuments = []

from docx import Document

doc = Document("2025_AnnualReport.docx")

print(
    "Paragraphs:",
    len(doc.paragraphs)
)

for paragraph in doc.paragraphs[:10]:
    print(paragraph.text)

from pypdf import PdfReader

def loadPdf(fileName):

    pdfFile = PdfReader(fileName)

    text = ""

    for page in pdfFile.pages:

        pageText = page.extract_text()

        if pageText:
            text += pageText

    return text

from docx import Document

def loadDocx(fileName):

    doc = Document(fileName)

    text = ""

    for paragraph in doc.paragraphs:

        text += paragraph.text
        text += "\n"

    return text

print(type(loadPdf))
print(type(loadDocx))

nvidiaText = loadPdf(
    "NVIDIA-2025-Annual-Report.pdf"
)

relianceText = loadPdf(
    "RIL-Integrated-Annual-Report-2024-25.pdf"
)

microsoftText = loadDocx(
    "2025_AnnualReport.docx"
)

print("NVIDIA:", len(nvidiaText))
print("Reliance:", len(relianceText))
print("Microsoft:", len(microsoftText))

allReports = [
    {
        "company": "NVIDIA",
        "text": nvidiaText
    },
    {
        "company": "Reliance",
        "text": relianceText
    },
    {
        "company": "Microsoft",
        "text": microsoftText
    }
]

print(
    "Companies loaded:",
    len(allReports)
)

companyChunks = []

chunkSize = 1000
overlapSize = 200

for report in allReports:

    companyName = report["company"]

    reportText = report["text"]

    startPosition = 0

    while startPosition < len(reportText):

        endPosition = (
            startPosition +
            chunkSize
        )

        companyChunks.append(
            {
                "company": companyName,
                "text": reportText[
                    startPosition:endPosition
                ]
            }
        )

        startPosition += (
            chunkSize -
            overlapSize
        )

print(
    "Total chunks:",
    len(companyChunks)
)

print(
    companyChunks[0]["company"]
)

print()

print(
    companyChunks[0]["text"][:300]
)

allChunkTexts = []

for chunk in companyChunks:

    allChunkTexts.append(
        chunk["text"]
    )

multiVectors = embeddingModel.encode(
    allChunkTexts,
    show_progress_bar=True
)

multiVectors = np.array(
    multiVectors,
    dtype=np.float32
)

print(
    "Embedding shape:",
    multiVectors.shape
)

multiIndex = faiss.IndexFlatL2(
    multiVectors.shape[1]
)

multiIndex.add(
    multiVectors
)

print(
    "Vectors stored:",
    multiIndex.ntotal
)

def retrieveFinancialContext(
    question,
    topK=5
):

    questionVector = embeddingModel.encode(
        [question]
    )

    questionVector = np.array(
        questionVector,
        dtype=np.float32
    )

    distances, positions = multiIndex.search(
        questionVector,
        topK
    )

    results = []

    for position in positions[0]:

        results.append(
            {
                "company":
                companyChunks[position]["company"],

                "text":
                companyChunks[position]["text"]
            }
        )

    return results

results = retrieveFinancialContext(
    "Which company is investing heavily in AI?"
)

for item in results:

    print(
        "\nCOMPANY:",
        item["company"]
    )

    print("=" * 50)

    print(
        item["text"][:500]
    )

def buildFinancialContext(
    question,
    topK=8
):

    retrievedChunks = retrieveFinancialContext(
        question,
        topK
    )

    context = ""

    for index, item in enumerate(
        retrievedChunks
    ):

        context += (
            f"\n[Source {index+1}] "
        )

        context += (
            f"Company: {item['company']}\n"
        )

        context += item["text"]

        context += "\n\n"

    return context

def askFinancialAgent(
    question
):

    context = buildFinancialContext(
        question
    )

    prompt = f"""
You are a senior equity research analyst.

Answer using only the provided context.

For every major statement,
mention the source number.

Context:
{context}

Question:
{question}

Provide:

1. Executive Summary

2. Key Findings

3. Supporting Evidence

4. Risks if mentioned
"""

    model = genai.GenerativeModel(
        "gemini-2.5-flash"
    )

    response = model.generate_content(
        prompt
    )

    return response.text

answer = askFinancialAgent(
    "Compare NVIDIA and Microsoft AI strategy"
)

print(answer)

def retrieveFinancialContext(
    question,
    topK=15
):

    questionVector = embeddingModel.encode(
        [question]
    )

    questionVector = np.array(
        questionVector,
        dtype=np.float32
    )

    distances, positions = multiIndex.search(
        questionVector,
        topK
    )

    results = []

    for position in positions[0]:

        results.append(
            {
                "company":
                companyChunks[position]["company"],

                "text":
                companyChunks[position]["text"]
            }
        )

    return results

results = retrieveFinancialContext(
    "Compare NVIDIA and Microsoft AI strategy"
)

for item in results:

    print(item["company"])

def retrieveByCompany(
    companyName,
    question,
    topK=5
):

    companyTexts = []
    companyPositions = []

    for index, chunk in enumerate(
        companyChunks
    ):

        if chunk["company"] == companyName:

            companyTexts.append(
                chunk["text"]
            )

            companyPositions.append(
                index
            )

    companyVectors = embeddingModel.encode(
        companyTexts
    )

    companyVectors = np.array(
        companyVectors,
        dtype=np.float32
    )

    companyIndex = faiss.IndexFlatL2(
        companyVectors.shape[1]
    )

    companyIndex.add(
        companyVectors
    )

    questionVector = embeddingModel.encode(
        [question]
    )

    questionVector = np.array(
        questionVector,
        dtype=np.float32
    )

    distances, positions = companyIndex.search(
        questionVector,
        topK
    )

    results = []

    for position in positions[0]:

        results.append(
            companyTexts[position]
        )

    return results

nvidiaResults = retrieveByCompany(
    "NVIDIA",
    "AI strategy"
)

print(
    nvidiaResults[0][:500]
)

microsoftResults = retrieveByCompany(
    "Microsoft",
    "AI strategy"
)

print(
    microsoftResults[0][:500]
)

def compareCompanies(
    companyA,
    companyB,
    question
):

    contextA = "\n".join(
        retrieveByCompany(
            companyA,
            question,
            topK=3
        )
    )

    contextB = "\n".join(
        retrieveByCompany(
            companyB,
            question,
            topK=3
        )
    )

    prompt = f"""
You are a senior equity research analyst.

Compare the two companies.

Company A:
{companyA}

Context:
{contextA}

Company B:
{companyB}

Context:
{contextB}

Question:
{question}

Provide:

1. Executive Summary

2. Comparison Table

3. Key Differences

4. Investment Implications
"""

    model = genai.GenerativeModel(
        "gemini-2.5-flash"
    )

    response = model.generate_content(
        prompt
    )

    return response.text

answer = compareCompanies(
    "NVIDIA",
    "Microsoft",
    "AI strategy"
)

print(answer)

faiss.write_index(
    multiIndex,
    "financialIndex.faiss"
)

np.save(
    "financialVectors.npy",
    multiVectors
)

import os

print(os.listdir())

import pickle

with open(
    "companyChunks.pkl",
    "wb"
) as file:

    pickle.dump(
        companyChunks,
        file
    )

print("Metadata saved")

from google.colab import files

files.download("financialIndex.faiss")

files.download("financialVectors.npy")

files.download("companyChunks.pkl")

























